name: tiktok
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  rest_client:
    path: packages/rest_client
  app_core:
    path: packages/app_core
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  flutter_launcher_icons: ^0.13.1
  flutter_bloc: ^8.1.3
  flutter_riverpod: ^2.3.6
  intl: ^0.18.0
  convex_bottom_bar: ^3.2.0
  custom_nested_scroll_view:
    git:
      url: https://github.com/idootop/custom_nested_scroll_view.git
  flutter_svg: ^2.0.7
  get_it: ^7.6.0
  injectable: 2.1.2
  dio: ^5.3.0
  pretty_dio_logger: ^1.3.1
  flutter_dotenv: ^5.1.0
  permission_handler: ^10.4.3
  universal_platform: ^1.0.0+1
  flutter_secure_storage: ^8.0.0
  go_router: ^9.1.1
  freezed_annotation: ^2.2.0
  dynamic_color: ^1.6.6
  shimmer: ^3.0.0
  auto_size_text: ^3.0.0
  reactive_forms: ^16.0.3
  styled_text: ^7.0.0
  material_design_icons_flutter: ^7.0.7296
  custom_sliding_segmented_control: ^1.7.5
  animations: ^2.0.7
  rounded_loading_button: ^2.1.0
  internet_connection_checker_plus: ^2.0.0
  shared_preferences: ^2.2.0
  pull_to_refresh: ^2.0.0
  firebase_storage: ^11.2.5
  firebase_core: ^2.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  freezed: ^2.4.1
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.1
  flutter_gen: ^5.3.1
  injectable_generator: ^2.1.6

# output assets generation
scripts: derry.yaml
flutter_gen:
  output: lib/gen/
  integrations:
    flutter_svg: true

  assets:
    enabled: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/logo/logo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo/logo.png"

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # generate: true
  assets:
    - assets/icons/png/
    - assets/icons/svg/
    - assets/icons/
    - assets/env/.env.dev
    - assets/env/.env.prod

  fonts:
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/ProximaNova/Proximanova-bold.otf
          weight: 700
        - asset: assets/fonts/ProximaNova/Proximanova-medium.otf
          weight: 500
        - asset: assets/fonts/ProximaNova/Proximanova-regular.otf
          weight: 400
        - asset: assets/fonts/ProximaNova/Proximanova-light.otf
          weight: 300

    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito/Nunito-Light.ttf
          weight: 300
