// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbKoli3AAzKXz49ql2xaF2l--m-dyZirs',
    appId: '1:363317058184:web:cfc3bb7f867bd32df19d3d',
    messagingSenderId: '363317058184',
    projectId: 'tiktok-clone-5acc6',
    authDomain: 'tiktok-clone-5acc6.firebaseapp.com',
    storageBucket: 'tiktok-clone-5acc6.appspot.com',
    measurementId: 'G-5SQTMD7MR9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmFum-6zdl7HOMX2T_etv5FUM3iCZhXY4',
    appId: '1:363317058184:android:f88cf6592717cb8ef19d3d',
    messagingSenderId: '363317058184',
    projectId: 'tiktok-clone-5acc6',
    storageBucket: 'tiktok-clone-5acc6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwOBcVRngYa7YGnNt9aTdlJBPFZnQvf94',
    appId: '1:363317058184:ios:4cf22b18f8c54f6af19d3d',
    messagingSenderId: '363317058184',
    projectId: 'tiktok-clone-5acc6',
    storageBucket: 'tiktok-clone-5acc6.appspot.com',
    iosClientId: '363317058184-03uudcpf8ku1nrvblk1foeg3og9fj1b2.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktok',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwOBcVRngYa7YGnNt9aTdlJBPFZnQvf94',
    appId: '1:363317058184:ios:be8bfc7d1f71f383f19d3d',
    messagingSenderId: '363317058184',
    projectId: 'tiktok-clone-5acc6',
    storageBucket: 'tiktok-clone-5acc6.appspot.com',
    iosClientId: '363317058184-gbvgj4n0ai3je37bonrco98rjgm7idhp.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktok.RunnerTests',
  );
}
